DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  email VARCHAR(512) NOT NULL,
  username VARCHAR(512) NOT NULL,
  password VARCHAR(512) NOT NULL
);

DROP TABLE IF EXISTS notes;

CREATE TABLE notes (
	id SERIAL PRIMARY KEY NOT NULL,
	username VARCHAR(512) NOT NULL,
	note VARCHAR(512) NOT NULL,
	done BOOLEAN DEFAULT FALSE
);
